openapi: 3.1.0
info:
  version: 1.0.0
  title: Water app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of water app
tags:
  - name: User
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://the-dominators-back-project.onrender.com
paths:
  /user/signup:
    post:
      $ref: ../swagger/path/user/singup.yaml
  /user/signin:
    post:
      $ref: ../swagger/path/user/singin.yaml
  /user/logout:
    post:
      $ref: ../swagger/path/user/logout.yaml
  /user/password-reset:
    post:
      $ref: ../swagger/path/user/pwd-reset.yaml
  /users/{userId}:
    get:
      $ref: ../swagger/path/userInfo/{id}/get.yaml
    patch:
      $ref: ../swagger/path/userInfo/{id}/patch.yaml
  /users/{userId}/avatarUrl:
    patch: 
      $ref: ../swagger/path/userInfo/{id}/patchAvatar.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
